export interface QuantHolding {
  sr: number;
  isin: string;
  name: string;
  symbol: string;
  rating: string;
  industry: string;
  quantity: number;
  marketValueLakhs: number;
  weight: number;
  ytm: string | null;
  type: "equity" | "reit" | "derivative" | "commodity" | "debt" | "money_market" | "others";
  position: "long" | "short";
}

export const QUANT_PORTFOLIO_HOLDINGS: QuantHolding[] = [
  // --- EQUITY & EQUITY RELATED ---
  {
    sr: 1,
    isin: "INE090A01021",
    name: "ICICI Bank Limited",
    symbol: "ICICIBANK.NS",
    rating: "N.A.",
    industry: "Banks",
    quantity: 4145208,
    marketValueLakhs: 57004.9,
    weight: 9.53,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 2,
    isin: "INE423A01024",
    name: "Adani Enterprises Limited",
    symbol: "ADANIENT.NS",
    rating: "N.A.",
    industry: "Metals & Minerals Trading",
    quantity: 1567103,
    marketValueLakhs: 47577.25,
    weight: 7.96,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 3,
    isin: "INE364U01010",
    name: "Adani Green Energy Limited",
    symbol: "ADANIGREEN.NS",
    rating: "N.A.",
    industry: "Power",
    quantity: 3181116,
    marketValueLakhs: 47468.61,
    weight: 7.94,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 4,
    isin: "INE397D01024",
    name: "Bharti Airtel Limited",
    symbol: "BHARTIARTL.NS",
    rating: "N.A.",
    industry: "Telecom - Services",
    quantity: 2384467,
    marketValueLakhs: 44160.33,
    weight: 7.38,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 5,
    isin: "INE406A01037",
    name: "Aurobindo Pharma Limited",
    symbol: "AUROPHARMA.NS",
    rating: "N.A.",
    industry: "Pharmaceuticals & Biotechnology",
    quantity: 1797304,
    marketValueLakhs: 28374.04,
    weight: 4.74,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 6,
    isin: "INE795G01014",
    name: "HDFC Life Insurance Co Ltd",
    symbol: "HDFCLIFE.NS",
    rating: "N.A.",
    industry: "Insurance",
    quantity: 4197202,
    marketValueLakhs: 24169.59,
    weight: 4.04,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 7,
    isin: "INE346A01027",
    name: "ICICI Prudential Asset Management Ltd",
    symbol: "ICICIPRU.NS",
    rating: "N.A.",
    industry: "Capital Markets",
    quantity: 649749,
    marketValueLakhs: 21569.07,
    weight: 3.61,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 8,
    isin: "INE213A01029",
    name: "Oil & Natural Gas Corporation Ltd.",
    symbol: "ONGC.NS",
    rating: "N.A.",
    industry: "Oil",
    quantity: 7198164,
    marketValueLakhs: 16908.49,
    weight: 2.83,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 9,
    isin: "INE040A01034",
    name: "HDFC Bank Limited",
    symbol: "HDFCBANK.NS",
    rating: "N.A.",
    industry: "Banks",
    quantity: 1918150,
    marketValueLakhs: 15305.88,
    weight: 2.56,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 10,
    isin: "INE121J01017",
    name: "Indus Towers Limited",
    symbol: "INDUSTOWER.NS",
    rating: "N.A.",
    industry: "Telecom - Services",
    quantity: 3753029,
    marketValueLakhs: 14700.61,
    weight: 2.46,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 11,
    isin: "INE676A01027",
    name: "Black Box Limited",
    symbol: "BBOX.NS",
    rating: "N.A.",
    industry: "IT - Services",
    quantity: 1414999,
    marketValueLakhs: 13402.87,
    weight: 2.24,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 12,
    isin: "INE0BS701011",
    name: "Premier Energies Limited",
    symbol: "PREMIERENE.NS",
    rating: "N.A.",
    industry: "Electrical Equipment",
    quantity: 1170731,
    marketValueLakhs: 12304.38,
    weight: 2.06,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 13,
    isin: "INE018A01030",
    name: "Larsen & Toubro Limited",
    symbol: "LT.NS",
    rating: "N.A.",
    industry: "Construction",
    quantity: 257775,
    marketValueLakhs: 10680.65,
    weight: 1.79,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 14,
    isin: "INE669C01036",
    name: "Tech Mahindra Limited",
    symbol: "TECHM.NS",
    rating: "N.A.",
    industry: "IT - Software",
    quantity: 588000,
    marketValueLakhs: 8259.64,
    weight: 1.38,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 15,
    isin: "INE081A01020",
    name: "Tata Steel Limited",
    symbol: "TATASTEEL.NS",
    rating: "N.A.",
    industry: "Ferrous Metals",
    quantity: 3828000,
    marketValueLakhs: 7198.94,
    weight: 1.20,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 16,
    isin: "INE155A01022",
    name: "Tata Motors Passenger Vehicles Limited",
    symbol: "TATAMOTORS.NS",
    rating: "N.A.",
    industry: "Automobiles",
    quantity: 1614400,
    marketValueLakhs: 5685.92,
    weight: 0.95,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 17,
    isin: "INE781S01027",
    name: "Ventive Hospitality Limited",
    symbol: "VENTIVE.NS",
    rating: "N.A.",
    industry: "Leisure Services",
    quantity: 793155,
    marketValueLakhs: 4978.24,
    weight: 0.83,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 18,
    isin: "INE271C01023",
    name: "DLF Limited",
    symbol: "DLF.NS",
    rating: "N.A.",
    industry: "Realty",
    quantity: 801776,
    marketValueLakhs: 4971.41,
    weight: 0.83,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 19,
    isin: "INE200M01039",
    name: "Varun Beverages Limited",
    symbol: "VBL.NS",
    rating: "N.A.",
    industry: "Beverages",
    quantity: 707625,
    marketValueLakhs: 3591.55,
    weight: 0.60,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 20,
    isin: "INE376G01013",
    name: "Biocon Ltd",
    symbol: "BIOCON.NS",
    rating: "N.A.",
    industry: "Pharmaceuticals & Biotechnology",
    quantity: 842500,
    marketValueLakhs: 3524.18,
    weight: 0.59,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 21,
    isin: "INE484J01027",
    name: "Godrej Properties Limited",
    symbol: "GODREJPROP.NS",
    rating: "N.A.",
    industry: "Realty",
    quantity: 182050,
    marketValueLakhs: 3398.15,
    weight: 0.57,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 22,
    isin: "INE918I01026",
    name: "Bajaj Finserv Ltd.",
    symbol: "BAJAJFINSV.NS",
    rating: "N.A.",
    industry: "Finance",
    quantity: 184250,
    marketValueLakhs: 3280.02,
    weight: 0.55,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 23,
    isin: "INE549H01021",
    name: "Anand Rathi Share & Stock Brokers Ltd",
    symbol: "ANANDRATHI.NS",
    rating: "N.A.",
    industry: "Capital Markets",
    quantity: 485064,
    marketValueLakhs: 2688.47,
    weight: 0.45,
    ytm: null,
    type: "equity",
    position: "long"
  },
  {
    sr: 24,
    isin: "INE154A01025",
    name: "ITC Limited",
    symbol: "ITC.NS",
    rating: "N.A.",
    industry: "Diversified FMCG",
    quantity: 609600,
    marketValueLakhs: 1749.25,
    weight: 0.29,
    ytm: null,
    type: "equity",
    position: "long"
  },

  // --- REIT ---
  {
    sr: 25,
    isin: "INE1JAR25012",
    name: "Knowledge Realty Trust",
    symbol: "KNOWLEDGE.REIT",
    rating: "N.A.",
    industry: "Realty",
    quantity: 2499900,
    marketValueLakhs: 2886.13,
    weight: 0.48,
    ytm: null,
    type: "reit",
    position: "long"
  },

  // --- DERIVATIVES (Hedging Shorts) ---
  {
    sr: 26,
    isin: "ITC280726",
    name: "ITC Limited Future Short",
    symbol: "ITC.NS",
    rating: "N.A.",
    industry: "Diversified FMCG",
    quantity: -608925,
    marketValueLakhs: -1757.05,
    weight: -0.29,
    ytm: null,
    type: "derivative",
    position: "short"
  },
  {
    sr: 27,
    isin: "BAJAJFINSV280726",
    name: "Bajaj Finserv Ltd. Future Short",
    symbol: "BAJAJFINSV.NS",
    rating: "N.A.",
    industry: "Finance",
    quantity: -184200,
    marketValueLakhs: -3301.6,
    weight: -0.55,
    ytm: null,
    type: "derivative",
    position: "short"
  },
  {
    sr: 28,
    isin: "GODREJPROP280726",
    name: "Godrej Properties Limited Future Short",
    symbol: "GODREJPROP.NS",
    rating: "N.A.",
    industry: "Realty",
    quantity: -182000,
    marketValueLakhs: -3405.04,
    weight: -0.57,
    ytm: null,
    type: "derivative",
    position: "short"
  },
  {
    sr: 29,
    isin: "BIOCON280726",
    name: "Biocon Ltd Future Short",
    symbol: "BIOCON.NS",
    rating: "N.A.",
    industry: "Pharmaceuticals & Biotechnology",
    quantity: -842500,
    marketValueLakhs: -3548.61,
    weight: -0.59,
    ytm: null,
    type: "derivative",
    position: "short"
  },
  {
    sr: 30,
    isin: "VBL280726",
    name: "Varun Beverages Limited Future Short",
    symbol: "VBL.NS",
    rating: "N.A.",
    industry: "Beverages",
    quantity: -707625,
    marketValueLakhs: -3614.55,
    weight: -0.60,
    ytm: null,
    type: "derivative",
    position: "short"
  },
  {
    sr: 31,
    isin: "DLF280726",
    name: "DLF Limited Future Short",
    symbol: "DLF.NS",
    rating: "N.A.",
    industry: "Realty",
    quantity: -800850,
    marketValueLakhs: -4998.51,
    weight: -0.84,
    ytm: null,
    type: "derivative",
    position: "short"
  },
  {
    sr: 32,
    isin: "TMPV280726",
    name: "Tata Motors Passenger Vehicles Future Short",
    symbol: "TATAMOTORS.NS",
    rating: "N.A.",
    industry: "Automobiles",
    quantity: -1614400,
    marketValueLakhs: -5729.51,
    weight: -0.96,
    ytm: null,
    type: "derivative",
    position: "short"
  },
  {
    sr: 33,
    isin: "TATASTEEL280726",
    name: "Tata Steel Limited Future Short",
    symbol: "TATASTEEL.NS",
    rating: "N.A.",
    industry: "Ferrous Metals",
    quantity: -3828000,
    marketValueLakhs: -7242.19,
    weight: -1.21,
    ytm: null,
    type: "derivative",
    position: "short"
  },
  {
    sr: 34,
    isin: "LT280726",
    name: "Larsen & Toubro Limited Future Short",
    symbol: "LT.NS",
    rating: "N.A.",
    industry: "Construction",
    quantity: -257775,
    marketValueLakhs: -10737.88,
    weight: -1.80,
    ytm: null,
    type: "derivative",
    position: "short"
  },
  {
    sr: 35,
    isin: "HDFCBANK280726",
    name: "HDFC Bank Limited Future Short",
    symbol: "HDFCBANK.NS",
    rating: "N.A.",
    industry: "Banks",
    quantity: -1918150,
    marketValueLakhs: -15400.83,
    weight: -2.58,
    ytm: null,
    type: "derivative",
    position: "short"
  },

  // --- COMMODITY DERIVATIVES (Commodity Futures) ---
  {
    sr: 36,
    isin: "SILVER040926",
    name: "SILVER ETCD 04 Sep 2026",
    symbol: "SILVER",
    rating: "N.A.",
    industry: "Commodity Metals",
    quantity: 14880,
    marketValueLakhs: 34010.17,
    weight: 5.69,
    ytm: null,
    type: "commodity",
    position: "long"
  },
  {
    sr: 37,
    isin: "CRUDEOIL200726",
    name: "Crude Oil ETCD 20 Jul 2026",
    symbol: "CRUDEOIL",
    rating: "N.A.",
    industry: "Commodity Energy",
    quantity: 466400,
    marketValueLakhs: 30861.69,
    weight: 5.16,
    ytm: null,
    type: "commodity",
    position: "long"
  },

  // --- DEBT INSTRUMENTS ---
  {
    sr: 38,
    isin: "IN0020240134",
    name: "6.92% GOI Sovereign Bond 18-Nov-2039",
    symbol: "IN10YT=RR", // Tracked relative to 10Y sovereign yield
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 6500000,
    marketValueLakhs: 6508.58,
    weight: 1.09,
    ytm: "6.91",
    type: "debt",
    position: "long"
  },
  {
    sr: 39,
    isin: "IN0020240126",
    name: "6.79% GOI Sovereign Bond 07-OCT-2034",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 3500000,
    marketValueLakhs: 3515.3,
    weight: 0.59,
    ytm: "6.72",
    type: "debt",
    position: "long"
  },
  {
    sr: 40,
    isin: "IN0020240118",
    name: "7.09% GOI Sovereign Bond 05-AUG-2054",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 3500000,
    marketValueLakhs: 3409.15,
    weight: 0.57,
    ytm: "7.31",
    type: "debt",
    position: "long"
  },
  {
    sr: 41,
    isin: "IN1520250227",
    name: "7.27% Gujarat State Development Loan - 17-Dec-2034",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 2500000,
    marketValueLakhs: 2488.34,
    weight: 0.42,
    ytm: "7.34",
    type: "debt",
    position: "long"
  },
  {
    sr: 42,
    isin: "IN2220240229",
    name: "7.23% Maharashtra State Development Loan - 04-Sep-2035",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 2500000,
    marketValueLakhs: 2471.95,
    weight: 0.41,
    ytm: "7.40",
    type: "debt",
    position: "long"
  },
  {
    sr: 43,
    isin: "IN0020250018",
    name: "6.9% GOI Sovereign Bond 15-Apr-2065",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 2500000,
    marketValueLakhs: 2324.49,
    weight: 0.39,
    ytm: "7.45",
    type: "debt",
    position: "long"
  },
  {
    sr: 44,
    isin: "IN0020250091",
    name: "6.48% GOI Sovereign Bond 06-Oct-2035",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 2000000,
    marketValueLakhs: 1962.26,
    weight: 0.33,
    ytm: "6.76",
    type: "debt",
    position: "long"
  },
  {
    sr: 45,
    isin: "IN0020210186",
    name: "5.74% GOI Sovereign Bond 15-Nov-2026",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 1600000,
    marketValueLakhs: 1600.97,
    weight: 0.27,
    ytm: "5.51",
    type: "debt",
    position: "long"
  },
  {
    sr: 46,
    isin: "IN0020210020",
    name: "6.64% GOI Sovereign Bond 16-Jun-2035",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 1166400,
    marketValueLakhs: 1155.45,
    weight: 0.19,
    ytm: "6.79",
    type: "debt",
    position: "long"
  },
  {
    sr: 47,
    isin: "IN0020220144",
    name: "7.29% GOI SGRB MAT Sovereign Green Bond 27-Jan-2033",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 1000000,
    marketValueLakhs: 1036.69,
    weight: 0.17,
    ytm: "6.61",
    type: "debt",
    position: "long"
  },
  {
    sr: 48,
    isin: "IN0020220151",
    name: "7.26% GOI MAT Sovereign Bond 06-Feb-2033",
    symbol: "IN10YT=RR",
    rating: "SOV",
    industry: "Sovereign Debt",
    quantity: 1000000,
    marketValueLakhs: 1032.64,
    weight: 0.17,
    ytm: "6.64",
    type: "debt",
    position: "long"
  },

  // --- MONEY MARKET INSTRUMENTS ---
  {
    sr: 49,
    isin: "INE180C14730",
    name: "Capriglobal Commercial Paper 31-Jul-2026",
    symbol: "CP_RATE",
    rating: "A1+",
    industry: "N.A.",
    quantity: 2500000,
    marketValueLakhs: 2483.89,
    weight: 0.42,
    ytm: "7.89",
    type: "money_market",
    position: "long"
  },
  {
    sr: 50,
    isin: "INE414G14UT3",
    name: "Muthoot Finance Ltd Commercial Paper 08-Sep-2026",
    symbol: "CP_RATE",
    rating: "A1+",
    industry: "N.A.",
    quantity: 1500000,
    marketValueLakhs: 1480.6,
    weight: 0.25,
    ytm: "6.93",
    type: "money_market",
    position: "long"
  },
  {
    sr: 51,
    isin: "INE261F16AE9",
    name: "NABARD Certificate of Deposit 19-Jan-2027",
    symbol: "CD_RATE",
    rating: "A1+",
    industry: "N.A.",
    quantity: 10000000,
    marketValueLakhs: 9632.96,
    weight: 1.61,
    ytm: "6.89",
    type: "money_market",
    position: "long"
  },
  {
    sr: 52,
    isin: "INE514E16CN1",
    name: "EXIM Bank Certificate of Deposit 11-Nov-2026",
    symbol: "CD_RATE",
    rating: "A1+",
    industry: "N.A.",
    quantity: 7500000,
    marketValueLakhs: 7321.26,
    weight: 1.22,
    ytm: "6.70",
    type: "money_market",
    position: "long"
  },
  {
    sr: 53,
    isin: "INE556F16BN1",
    name: "SIDBI Certificate of Deposit 27-Oct-2026",
    symbol: "CD_RATE",
    rating: "A1+",
    industry: "N.A.",
    quantity: 1000000,
    marketValueLakhs: 978.43,
    weight: 0.16,
    ytm: "6.82",
    type: "money_market",
    position: "long"
  },
  {
    sr: 54,
    isin: "IN002026Y071",
    name: "182 Days Treasury Bill 19-Nov-2026",
    symbol: "TBILL_RATE",
    rating: "SOV",
    industry: "N.A.",
    quantity: 5000000,
    marketValueLakhs: 4897.65,
    weight: 0.82,
    ytm: "5.41",
    type: "money_market",
    position: "long"
  },
  {
    sr: 55,
    isin: "IN002025Z419",
    name: "364 Days Treasury Bill 15-JAN-2027",
    symbol: "TBILL_RATE",
    rating: "SOV",
    industry: "N.A.",
    quantity: 5000000,
    marketValueLakhs: 4856.94,
    weight: 0.81,
    ytm: "5.43",
    type: "money_market",
    position: "long"
  },
  {
    sr: 56,
    isin: "IN000927C052",
    name: "0% GS2027 CSTRIP 12 Sep 2027 Government Strip",
    symbol: "TBILL_RATE",
    rating: "SOV",
    industry: "N.A.",
    quantity: 2024000,
    marketValueLakhs: 1888.06,
    weight: 0.32,
    ytm: "5.89",
    type: "money_market",
    position: "long"
  },
  {
    sr: 57,
    isin: "IN000926C054",
    name: "0% GS2027 CSTRIP 12 Sep 2026 Government Strip",
    symbol: "TBILL_RATE",
    rating: "SOV",
    industry: "N.A.",
    quantity: 1300000,
    marketValueLakhs: 1286.18,
    weight: 0.22,
    ytm: "5.37",
    type: "money_market",
    position: "long"
  },
  {
    sr: 58,
    isin: "IN002025Z500",
    name: "364 Days Treasury Bill 19-Mar-2027",
    symbol: "TBILL_RATE",
    rating: "SOV",
    industry: "N.A.",
    quantity: 200000,
    marketValueLakhs: 192.46,
    weight: 0.03,
    ytm: "5.48",
    type: "money_market",
    position: "long"
  },

  // --- OTHERS ---
  {
    sr: 59,
    isin: "INF204KB17I5",
    name: "Nippon India ETF Gold Bees",
    symbol: "GOLDBEES.NS",
    rating: "N.A.",
    industry: "N.A.",
    quantity: 43527442,
    marketValueLakhs: 50478.77,
    weight: 8.44,
    ytm: null,
    type: "others",
    position: "long"
  },
  {
    sr: 60,
    isin: "INF204KC1402",
    name: "Nippon India MF - Nippon India Silver ETF",
    symbol: "SILVERBEES.NS",
    rating: "N.A.",
    industry: "N.A.",
    quantity: 4262802,
    marketValueLakhs: 9072.1,
    weight: 1.52,
    ytm: null,
    type: "others",
    position: "long"
  },
  {
    sr: 61,
    isin: "INF966L01BF7",
    name: "QUANT GILT FUND - DIRECT PLAN - GROWTH",
    symbol: "GILT_PROXY",
    rating: "N.A.",
    industry: "N.A.",
    quantity: 999950,
    marketValueLakhs: 125.58,
    weight: 0.02,
    ytm: null,
    type: "others",
    position: "long"
  },
  {
    sr: 62,
    isin: "INCBLO010726",
    name: "Tri Party Repo (TREPs) Cash Equivalent",
    symbol: "TREPS_PROXY",
    rating: "N.A.",
    industry: "N.A.",
    quantity: 367790.9,
    marketValueLakhs: 36779.09,
    weight: 6.15,
    ytm: "5.78",
    type: "others",
    position: "long"
  },
  {
    sr: 63,
    isin: "NCA-NETCURRENTASSETS",
    name: "Net Current Assets (Receivables/Payables)",
    symbol: "NCA_PROXY",
    rating: "N.A.",
    industry: "N.A.",
    quantity: 1,
    marketValueLakhs: 28082.06,
    weight: 4.70,
    ytm: null,
    type: "others",
    position: "long"
  }
];
